# Generated by Django 4.2.11 on 2024-05-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdManager', '0002_alter_passwordentry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
    ]
