# Generated by Django 4.2.11 on 2024-05-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwdManager', '0004_passwordentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
    ]
